# Generated by Django 5.0 on 2024-02-19 10:45

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to=blog.models.upload_to),
        ),
    ]
